### ISSUE TITLE
请问下代码实现思路是什么？如何对齐python的模型结构和输出呢

### ISSUE THREAD

**Issue by dawnranger** [ztxz16/fastllm#10]
是直接对照 huggingface 版的python代码来实现的吗
https://huggingface.co/THUDM/chatglm-6b-int8/blob/main/modeling_chatglm.py

**Comment by ztxz16** [comment]
是的

**Comment by dawnranger** [comment]
目前看到解码部分好像就是简单的greedy search，原版是用的beam_sample算法的

**Comment by ztxz16** [comment]
> 目前看到解码部分好像就是简单的greedy search，原版是用的beam_sample算法的

现在已经支持采样参数了
