### ISSUE TITLE
关于导入from fastllm_pytools import llm 报.so库的问题

### ISSUE THREAD

**Issue by White-Friday** [ztxz16/fastllm#102]
出现以下问题： anaconda3/envs/common_env/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found

**Comment by heavenkiller2018** [comment]
我也是出现同样类似的问题，有解决方案吗?如何解决的？

**Comment by FdyCN** [comment]
我也遇到了这个问题。。。请问有什么解决方法么？@White-Friday @ztxz16

**Comment by FdyCN** [comment]
> 我也是出现同样类似的问题，有解决方案吗?如何解决的？ @White-Friday @ztxz16

@heavenkiller2018 不知道你解决没有，我是参考这个回答：https://github.com/rstudio/reticulate/issues/1282#issuecomment-1272473007

我在conda中使用指令做了对应的升级：
```
conda install -c conda-forge libstdcxx-ng
```

之后解决了这个问题。你如果没解决的话可以试试看。

**Comment by heavenkiller2018** [comment]
@FdyCN 解决了，我把libstdc++.so.6.0.30 copy到目标目录就好了。参考了：[解决 libstdc++.so.6: version ‘GLIBCXX_3.4.30‘ not found 问题_version `glibcxx_3.4.30' not found_bohrium的博客-CSDN博客](https://blog.csdn.net/bohrium/article/details/126546521)
