### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_pyfastllm)

### ISSUE THREAD

**Issue by neverstoplearn** [ztxz16/fastllm#105]
更新后出来错误
Traceback (most recent call last):
  File "web_api.py", line 7, in <module>
    import pyfastllm # 或fastllm
ImportError: dynamic module does not define module export function (PyInit_pyfastllm)

**Comment by neverstoplearn** [comment]
> 更新后出来错误 Traceback (most recent call last): File "web_api.py", line 7, in import pyfastllm # 或fastllm ImportError: dynamic module does not define module export function (PyInit_pyfastllm)

将编译好的动态库放置demo目录下可以解决

**Comment by zoey-zy998** [comment]
哪个编译好的动态库

**Comment by neverstoplearn** [comment]
build-py目录下的动态库

**Comment by zoey-zy998** [comment]
我把build-py生成的文件 pyfastllm.cpython-36m-x86_64-linux-gnu.so*
放到demo目录下还是报错

**Comment by zoey-zy998** [comment]
以及放到说的/usr/local/python3.8/site-packages下也报同样的bug

**Comment by zoey-zy998** [comment]
解决了，编译的时候这两个要保持一样
![image](https://github.com/ztxz16/fastllm/assets/55828495/9970e475-1acc-4a47-afcc-81a4c944a269)
