### ISSUE TITLE
baichuan除了13B，可以试试

### ISSUE THREAD

**Issue by liaoweiguo** [ztxz16/fastllm#110]

**Comment by ztxz16** [comment]
> 这个模型跑不通，https://huggingface.co/baichuan-inc/Baichuan-13B-Chat 期待适配下

现在应该可以了

**Comment by liaoweiguo** [comment]
model = llm.from_hf(model, tokenizer, dtype = "int8")
convert ( 83 / 83 )
Warmup...
FastLLM Error: Linear's weight's shape's size should be 2.

terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'

**Comment by liaoweiguo** [comment]
> > 这个模型跑不通，https://huggingface.co/baichuan-inc/Baichuan-13B-Chat 期待适配下
> 
> 现在应该可以了

有试过吗，我在model = llm.from_hf(model, tokenizer, dtype = "int8")
这一步报错

**Comment by liaoweiguo** [comment]
OK了

**Comment by cjcio** [comment]
> OK了

请问怎么解决的，我也遇到这个问题了

**Comment by TylunasLi** [comment]
> > ```
> > model = llm.from_hf(model, tokenizer, dtype = "int8") 
> > ```
> > ```
> > convert ( 83 / 83 ) 
> > Warmup... 
> > FastLLM Error: Linear's weight's shape's size should be 2.
> > ```
> > terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits, std::allocator >'
> 
> 请问这个是怎么解决的，我也遇到了

报错是因为没有读取到与模型结构相匹配的权重导致的。
请问你转换的原始模型是什么？ convert显示的权重数量是多少？ 
另外，不支持从已经量化的模型加载和加速。

**Comment by turbosxy** [comment]
> > > ```
> > > model = llm.from_hf(model, tokenizer, dtype = "int8") 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > convert ( 83 / 83 ) 
> > > Warmup... 
> > > FastLLM Error: Linear's weight's shape's size should be 2.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits, std::allocator >'
> > 
> > 
> > 请问这个是怎么解决的，我也遇到了
> 
> 报错是因为没有读取到与模型结构相匹配的权重导致的。 请问你转换的原始模型是什么？ convert显示的权重数量是多少？ 另外，不支持从已经量化的模型加载和加速。

我的原始模型是chatglm3-6b，我lora微调后的模型进行了convert。权重数量255.模型没有量化过
