### ISSUE TITLE
运行一段时间后偶发异常terminate called after throwing an instance of 'char const*'

### ISSUE THREAD

**Issue by wangyumu** [ztxz16/fastllm#114]
使用chatglm-6b-int8.flm在24G的GPU上运行，理论上内存是足够用的。

但是运行一段时间后会异常，控制台报错：
terminate called after throwing an instance of 'char const*'

python会进入<defunct>状态，挂住。

请问：
1. 是否有其他的详细日志供排查分析？
2. 进入这个状态后，是否有办法自动重启？

**Comment by ztxz16** [comment]
gdb可以看到报错信息吗

**Comment by wangyumu** [comment]
看不到，我用python基本调用的，也没有看到core等信息。

不过我这个问题好像出现在chatglm-6b-int8.flm这个版本，运行chatglm2-6b-int8.flm版本就一直没出现。

我再观察看看，如果没问题我就关闭掉issue。

**Comment by wangyumu** [comment]
没有继续出现，先关闭了。

怀疑max_tokens设置的比较大，造成用chatglm第一版时出现异常。

**Comment by lxp521125** [comment]
当提交的文本大一点，我也遇到了这个问题，模型用的是chatglm2-6b,显卡4090：

Error: cublas error.
terminate called after throwing an instance of 'char const*'
已放弃 (核心已转储)
