### ISSUE TITLE
OSError: libcublas.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zoey-zy998** [ztxz16/fastllm#143]
下载完fastllm之后
cd fastllm
cmake . -B build -DCMAKE_CUDA_COMPILER=/usr/local/cuda-12.1/bin/nvcc -DTCNN_CUDA_ARCHITECTURES=61 -DUSE_CUDA=ON
修改为     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread --std=c++17 -O2")
cd tools && python setup.py install
上述操作后，from fastllm import llm 报错
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/fastllm/build/tools/fastllm_pytools/llm.py", line 9, in <module>
    fastllm_lib = ctypes.cdll.LoadLibrary(os.path.join(os.path.split(os.path.realpath(__file__))[0], "libfastllm_tools.so"))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 447, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.12: cannot open shared object file: No such file or directory

**Comment by zoey-zy998** [comment]
已解决

**Comment by Lsjay3** [comment]
你好，你是怎么解决的呢？

**Comment by Lsjay3** [comment]
> 已解决

你好，你是怎么解决的呢？

**Comment by lichengyang666** [comment]
同问 咋解决的呢

**Comment by Lsjay3** [comment]
来信收悉，顺祝恭安！
