### ISSUE TITLE
我在尝试用pyfastllm里面的web_api这个有办法指定或者多个gpu启动吗？

### ISSUE THREAD

**Issue by TIXhjq** [ztxz16/fastllm#152]

**Comment by wildkid1024** [comment]
并不能，默认会在gpu0上加载，多卡加载的功能还未开发，

**Comment by TylunasLi** [comment]
作者还没有开发，默认跑在CUDA设备0上。目前只能通过为程序指定环境变量CUDA_ViSIBLE_DEVIiCES的方法切换GPU。

**Comment by TIXhjq** [comment]
嗯嗯好的谢谢，我在一个卡上起了一个服务，看起来也问题不大😂
