### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by YueGeek** [ztxz16/fastllm#16]
流程：
（1）根据readme.md，构建编译环境，状态：编译成功（存在main、quant文件）；
（2）将自己微调（ptv2）后的模型导出为浮点模型（/root/autodl-tmp/chatglm-6b.bin，大小25GB），状态：导出成功；
（3）利用命令./quant -m chatglm -p /root/autodl-tmp/chatglm-6b.bin -o /root/autodl-tmp/chatglm-6b-int8.bin -b 8 将浮点模型导出为int8模型，此步骤发生报错。

报错信息如下：
Segmentation fault (core dumped)
![image](https://github.com/ztxz16/fastllm/assets/96854562/9200b3f9-e173-431a-8cf6-d5296e813f48)

环境：
服务器平台-AutoDL
Ubantu-20.04
CMake-3.16.3
CUDA-11.3
GPU-RTX2080Ti(11GB)
内存-40GB

**Comment by ztxz16** [comment]
> 流程： （1）根据readme.md，构建编译环境，状态：编译成功（存在main、quant文件）； （2）将自己微调（ptv2）后的模型导出为浮点模型（/root/autodl-tmp/chatglm-6b.bin，大小25GB），状态：导出成功； （3）利用命令./quant -m chatglm -p /root/autodl-tmp/chatglm-6b.bin -o /root/autodl-tmp/chatglm-6b-int8.bin -b 8 将浮点模型导出为int8模型，此步骤发生报错。
> 
> 报错信息如下： Segmentation fault (core dumped) ![image](https://user-images.githubusercontent.com/96854562/241869867-9200b3f9-e173-431a-8cf6-d5296e813f48.png)
> 
> 环境： 服务器平台-AutoDL Ubantu-20.04 CMake-3.16.3 CUDA-11.3 GPU-RTX2080Ti(11GB) 内存-40GB

现在应该修复了

**Comment by YueGeek** [comment]
> > 流程： （1）根据readme.md，构建编译环境，状态：编译成功（存在main、quant文件）； （2）将自己微调（ptv2）后的模型导出为浮点模型（/root/autodl-tmp/chatglm-6b.bin，大小25GB），状态：导出成功； （3）利用命令./quant -m chatglm -p /root/autodl-tmp/chatglm-6b.bin -o /root/autodl-tmp/chatglm-6b-int8.bin -b 8 将浮点模型导出为int8模型，此步骤发生报错。
> > 报错信息如下： Segmentation fault (core dumped) ![image](https://user-images.githubusercontent.com/96854562/241869867-9200b3f9-e173-431a-8cf6-d5296e813f48.png)
> > 环境： 服务器平台-AutoDL Ubantu-20.04 CMake-3.16.3 CUDA-11.3 GPU-RTX2080Ti(11GB) 内存-40GB
> 
> 现在应该修复了

感谢感谢，稍后会尝试一下
