### ISSUE TITLE
运行提示：段错误

### ISSUE THREAD

**Issue by RamSong** [ztxz16/fastllm#175]
(a) [ramsong@localhost build]$ ./main -p ./chatglm2-6b-int4.flm -l -t 8
AVX: OFF
AVX2: OFF
AARCH64: ON
Neon FP16: ON
Neon DOT: ON
段错误

环境
gcc 版本 12.1.0
Arch Linux 最新
Python 3.11.3

**Comment by ztxz16** [comment]
一般原因是内存爆了
如果不是的话可能要GDB看下出错的地方

**Comment by zby1211** [comment]
我也是段错误

**Comment by zby1211** [comment]
我也是段错误，查了一下发现是libc.so.6的register_printf_modifier寄了
正在找解决方法。。。

**Comment by TylunasLi** [comment]
demo代码等非核心部分，缺少错误处理逻辑。

> (a) [ramsong@localhost build]$ ./main -p ./chatglm2-6b-int4.flm -l -t 8 AVX: OFF AVX2: OFF AARCH64: ON Neon FP16: ON Neon DOT: ON 段错误
> 
> 环境 gcc 版本 12.1.0 Arch Linux 最新 Python 3.11.3

像这个就是 -l 后面少参数没处理，还有几个工具的模型文件名不对也会直接段错误。

尽量当main，webui和benchmark是方便理解库如何使用的demo就好。

**Comment by TylunasLi** [comment]
经过调试，发现这个问题是fastllm::ChatGLM类的构造函数在没有加载模型时调用GetVersion()，导致版本号默认为1，因此加载ChatGLM2时，WeightMap::load'FromFile()该用lowMemMode加载的embeddings部分没有记录文件名和位置。
