### ISSUE TITLE
Android端运行，文件传输问题

### ISSUE THREAD

**Issue by Jaren1907** [ztxz16/fastllm#18]
`ReadMe`中讲需要把main和模型push到`termux`目录下
当前目录是`/data/data/com.termux/files/home/`
但是`adb push`传输文件时会提示`Permission denied`

请问是否必须要将手机root，需要通过什么方式将文件传输至`termux`目录下呢？
谢谢！

**Comment by ztxz16** [comment]
不用root，我一般是把文件拷到手机里（比如拷到downloads目录），然后在termux用cp命令里面把文件从downloads目录拷到termux的根目录

**Comment by Jaren1907** [comment]
感谢答复，已按照你提供的方式将`main`和以及模型文件拷贝到termux根目录下
并且已执行`termux-setup-storage`获得读取手机文件的权限
但执行`./main`的时候仍然提示`Permission denied`

**Comment by Jaren1907** [comment]
感谢答复，已按照你提供的方式将main和以及模型文件拷贝到termux根目录下
并且已执行`termux-setup-storage`获得读取手机文件的权限
但执行`./main`的时候仍然提示`Permission denied`

**Comment by ztxz16** [comment]
> 感谢答复，已按照你提供的方式将`main`和以及模型文件拷贝到termux根目录下 并且已执行`termux-setup-storage`获得读取手机文件的权限 但执行`./main`的时候仍然提示`Permission denied`

要在termux里给main执行权限（chmod 777 main)
