### ISSUE TITLE
GPU编译失败

### ISSUE THREAD

**Issue by jackaihfia2334** [ztxz16/fastllm#187]
nvcc fatal   : Unsupported gpu architecture 'compute_native'
make[2]: *** [CMakeFiles/fastllm.dir/build.make:244: CMakeFiles/fastllm.dir/src/devices/cuda/fastllm-cuda.cu.o] Error 1

**Comment by TylunasLi** [comment]
见 #107

**Comment by jackaihfia2334** [comment]
thanks
