### ISSUE TITLE
推理结果 ChatGLM:<eop><eop><eop><eop><eop>

### ISSUE THREAD

**Issue by rayle01** [ztxz16/fastllm#19]
转换完成的模型，推理结果只有<eop>是什么原因？
1. tools/chatglm_export.py  ../chatglm-6b.bin
2. (CPU) build/quant -m chatglm -p chatglm-6b.bin -o chatglm-6b-int8.bin -b 8
3. 推理(CPU/GPU)： build/main -m chatglm -p chatglm-6b-int8.bin
结果

Load (368 / 368) 
Warmup...
finish.
用户: 1
ChatGLM: '<eop...'

请教是什么原因？

**Comment by ztxz16** [comment]
> 

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
print(token.get_vocab().get("<eop>"))

我试了下这个，输出确实就是130005

**Comment by rayle01** [comment]
修改下 src/chatglm.cpp中的id正常输出了

277         ids.push_back(150001);
278         ids.push_back(150004);

308             if (ret == 150005) {
338             Data inputIds = Data(DataType::FLOAT32, {1, 1}, {150004});

**Comment by rayle01** [comment]
已定位原因，15000+问题是刚开源时下载的模型文件，后来THUDM/chatglm-6b更新后没拉到最新的
