### ISSUE TITLE
Error  in build-py

### ISSUE THREAD

**Issue by jackaihfia2334** [ztxz16/fastllm#190]
CMake Error at CMakeLists.txt:50 (add_subdirectory):
  The source directory

    /data/llm/code/fastllm/third_party/pybind11

  does not contain a CMakeLists.txt file.

-- Found Python3: /usr/bin/python3.10 (found version "3.10.6") found components: Interpreter 
CMake Error at CMakeLists.txt:60 (pybind11_extension):
  Unknown CMake command "pybind11_extension".

-- Configuring incomplete, errors occurred!
See also "/data/llm/code/fastllm/build-py/CMakeFiles/CMakeOutput.log".

**Comment by aoyifei** [comment]
meet with same problem, anyone could help to correct the python api build part?
