### ISSUE TITLE
关于老机器指令集问题的编译建议

### ISSUE THREAD

**Issue by W-William** [ztxz16/fastllm#194]
本机配置：
![image](https://github.com/ztxz16/fastllm/assets/62868186/910ea544-bbd8-49dd-a267-4349e6fca798)

初始cmake编译选项下，编译报错
![image](https://github.com/ztxz16/fastllm/assets/62868186/0f2bba17-27da-468f-bd10-1968611191e9)

经搜索发现，带有“__mm256_XXXXXX_XX ”字样的函数都是Intel指令集函数，可以在[https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=3828,301,2553](url)中查询到指令信息

所以更改【项目根目录】/CMakeLists.txt文件中第20行左右为：
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread --std=c++17 -O2 -mavx -mavx2 -mfma -mf16c")`

在本机可以编译通过

在其他类似的老机器环境下，如依然出现此类报错，可以在[https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=3828,301,2553](url)中搜索该函数
在详细信息处找到其“CPUID Flags”属性
然后在CMakeLists.txt中加入编译选项“-mXXX”即可
例如我需要额外的该支持：
![image](https://github.com/ztxz16/fastllm/assets/62868186/1b5b3b32-b318-43ba-8980-2084b9d8f5c5)
于是加入编译选项“-mf16c”

**Comment by W-William** [comment]
追加一条建议
就是如果编译的时候真的出了很多报错
那么很可能就是机器真的不支持
然后即使编译过了，运行也大概率会报illegal hardware instruction error错误（）
所以感觉最好还是老老实实搞新机吧（）

**Comment by allendred** [comment]
编译过了还是会报错

**Comment by TylunasLi** [comment]
尝试对仅有AVX而无AVX2的环境编译做了支持。可以试下 TylunasLi@72a6d54 。
目前在Xeon E5 2665 (x79主板) 上测试通过。
