### ISSUE TITLE
make -j报错

### ISSUE THREAD

**Issue by Dominicbrian** [ztxz16/fastllm#198]
**make -j报错，好像和其他几位报的错误不太一样，不知道是不是一样的解决方式**

[  2%] Building CXX object CMakeFiles/fastllm.dir/src/fastllm.cpp.o
[  5%] Building CXX object CMakeFiles/fastllm_tools.dir/src/fastllm.cpp.o
[  8%] Building CXX object CMakeFiles/fastllm.dir/src/devices/cpu/cpudevice.cpp.o
[ 11%] Building CXX object CMakeFiles/fastllm_tools.dir/src/devices/cpu/cpudevice.cpp.o
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp: In function 'int fastllm::DotU4U8(uint8_t*, uint8_t*, int)':
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp:139:29: error: '_mm256_set_m128i' was not declared in this scope
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
/home/nlp/Weight/fastllm/src/fastllm.cpp: In member function 'void fastllm::Data::CalcWeightSum()':
/home/nlp/Weight/fastllm/src/fastllm.cpp:593:31: error: '_mm256_set_m128i' was not declared in this scope
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp: In function 'int fastllm::DotU4U8(uint8_t*, uint8_t*, int)':
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp:139:29: error: '_mm256_set_m128i' was not declared in this scope
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp:139:29: note: suggested alternative: '_mm256_set_epi8'
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
                             _mm256_set_epi8
/home/nlp/Weight/fastllm/src/fastllm.cpp:593:31: note: suggested alternative: '_mm256_set_epi8'
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
                               _mm256_set_epi8
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp:139:29: note: suggested alternative: '_mm256_set_epi8'
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
                             _mm256_set_epi8
/home/nlp/Weight/fastllm/src/fastllm.cpp: In member function 'void fastllm::Data::CalcWeightSum()':
/home/nlp/Weight/fastllm/src/fastllm.cpp:593:31: error: '_mm256_set_m128i' was not declared in this scope
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
/home/nlp/Weight/fastllm/src/fastllm.cpp:593:31: note: suggested alternative: '_mm256_set_epi8'
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
                               _mm256_set_epi8
CMakeFiles/fastllm.dir/build.make:75: recipe for target 'CMakeFiles/fastllm.dir/src/fastllm.cpp.o' failed
make[2]: *** [CMakeFiles/fastllm.dir/src/fastllm.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/fastllm_tools.dir/build.make:75: recipe for target 'CMakeFiles/fastllm_tools.dir/src/fastllm.cpp.o' failed
make[2]: *** [CMakeFiles/fastllm_tools.dir/src/fastllm.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/fastllm_tools.dir/build.make:131: recipe for target 'CMakeFiles/fastllm_tools.dir/src/devices/cpu/cpudevice.cpp.o' failed
make[2]: *** [CMakeFiles/fastllm_tools.dir/src/devices/cpu/cpudevice.cpp.o] Error 1
CMakeFiles/Makefile2:222: recipe for target 'CMakeFiles/fastllm_tools.dir/all' failed
make[1]: *** [CMakeFiles/fastllm_tools.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/fastllm.dir/build.make:131: recipe for target 'CMakeFiles/fastllm.dir/src/devices/cpu/cpudevice.cpp.o' failed
make[2]: *** [CMakeFiles/fastllm.dir/src/devices/cpu/cpudevice.cpp.o] Error 1
CMakeFiles/Makefile2:92: recipe for target 'CMakeFiles/fastllm.dir/all' failed
make[1]: *** [CMakeFiles/fastllm.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Dominicbrian** [comment]
**我重新试了一下，第一遍的时候好像是如下的错误，后续在编译会报如上的错误**

[  5%] Building CXX object CMakeFiles/fastllm.dir/src/device.cpp.o
[  5%] Building CXX object CMakeFiles/fastllm.dir/src/fastllm.cpp.o
[  8%] Building CXX object CMakeFiles/fastllm.dir/src/model.cpp.o
[ 11%] Building CXX object CMakeFiles/fastllm_tools.dir/src/device.cpp.o
[ 13%] Building CXX object CMakeFiles/fastllm.dir/src/executor.cpp.o
[ 19%] Building CXX object CMakeFiles/fastllm.dir/src/devices/cpu/cpudevicebatch.cpp.o
[ 19%] Building CXX object CMakeFiles/fastllm_tools.dir/src/model.cpp.o
[ 27%] Building CXX object CMakeFiles/fastllm_tools.dir/src/executor.cpp.o
[ 30%] Building CXX object CMakeFiles/fastllm_tools.dir/src/fastllm.cpp.o
[ 30%] Building CXX object CMakeFiles/fastllm.dir/src/devices/cpu/cpudevice.cpp.o
[ 30%] Building CXX object CMakeFiles/fastllm_tools.dir/src/devices/cpu/cpudevicebatch.cpp.o
[ 38%] Building CXX object CMakeFiles/fastllm.dir/src/models/moss.cpp.o
[ 38%] Building CXX object CMakeFiles/fastllm_tools.dir/src/devices/cpu/cpudevice.cpp.o
[ 38%] Building CXX object CMakeFiles/fastllm.dir/src/models/chatglm.cpp.o
[ 41%] Building CXX object CMakeFiles/fastllm_tools.dir/src/models/chatglm.cpp.o
[ 47%] Building CXX object CMakeFiles/fastllm.dir/src/models/basellm.cpp.o
[ 47%] Building CXX object CMakeFiles/fastllm.dir/src/models/llama.cpp.o
[ 50%] Building CXX object CMakeFiles/fastllm.dir/src/devices/cuda/cudadevice.cpp.o
[ 55%] Building CXX object CMakeFiles/fastllm_tools.dir/src/devices/cuda/cudadevice.cpp.o
[ 58%] Building CUDA object CMakeFiles/fastllm.dir/src/devices/cuda/fastllm-cuda.cu.o
[ 63%] Building CXX object CMakeFiles/fastllm_tools.dir/src/models/moss.cpp.o
[ 63%] Building CXX object CMakeFiles/fastllm_tools.dir/src/models/llama.cpp.o
[ 63%] Building CXX object CMakeFiles/fastllm.dir/src/devices/cuda/cudadevicebatch.cpp.o
[ 66%] Building CXX object CMakeFiles/fastllm_tools.dir/src/devices/cuda/cudadevicebatch.cpp.o
[ 69%] Building CUDA object CMakeFiles/fastllm_tools.dir/src/devices/cuda/fastllm-cuda.cu.o
[ 72%] Building CXX object CMakeFiles/fastllm_tools.dir/src/models/basellm.cpp.o
[ 75%] Building CXX object CMakeFiles/fastllm_tools.dir/tools/src/pytools.cpp.o
/home/nlp/Weight/fastllm/src/fastllm.cpp: In member function 'void fastllm::Data::CalcWeightSum()':
/home/nlp/Weight/fastllm/src/fastllm.cpp:593:31: error: '_mm256_set_m128i' was not declared in this scope
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
/home/nlp/Weight/fastllm/src/fastllm.cpp:593:31: note: suggested alternative: '_mm256_set_epi8'
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
                               _mm256_set_epi8
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp: In function 'int fastllm::DotU4U8(uint8_t*, uint8_t*, int)':
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp:139:29: error: '_mm256_set_m128i' was not declared in this scope
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp:139:29: note: suggested alternative: '_mm256_set_epi8'
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
                             _mm256_set_epi8
/home/nlp/Weight/fastllm/src/fastllm.cpp: In member function 'void fastllm::Data::CalcWeightSum()':
/home/nlp/Weight/fastllm/src/fastllm.cpp:593:31: error: '_mm256_set_m128i' was not declared in this scope
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
/home/nlp/Weight/fastllm/src/fastllm.cpp:593:31: note: suggested alternative: '_mm256_set_epi8'
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
                               _mm256_set_epi8
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp: In function 'int fastllm::DotU4U8(uint8_t*, uint8_t*, int)':
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp:139:29: error: '_mm256_set_m128i' was not declared in this scope
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
/home/nlp/Weight/fastllm/src/devices/cpu/cpudevice.cpp:139:29: note: suggested alternative: '_mm256_set_epi8'
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
                             _mm256_set_epi8
CMakeFiles/fastllm_tools.dir/build.make:75: recipe for target 'CMakeFiles/fastllm_tools.dir/src/fastllm.cpp.o' failed
make[2]: *** [CMakeFiles/fastllm_tools.dir/src/fastllm.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/fastllm.dir/build.make:75: recipe for target 'CMakeFiles/fastllm.dir/src/fastllm.cpp.o' failed
make[2]: *** [CMakeFiles/fastllm.dir/src/fastllm.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/fastllm.dir/build.make:131: recipe for target 'CMakeFiles/fastllm.dir/src/devices/cpu/cpudevice.cpp.o' failed
make[2]: *** [CMakeFiles/fastllm.dir/src/devices/cpu/cpudevice.cpp.o] Error 1
CMakeFiles/fastllm_tools.dir/build.make:131: recipe for target 'CMakeFiles/fastllm_tools.dir/src/devices/cpu/cpudevice.cpp.o' failed
make[2]: *** [CMakeFiles/fastllm_tools.dir/src/devices/cpu/cpudevice.cpp.o] Error 1
CMakeFiles/Makefile2:222: recipe for target 'CMakeFiles/fastllm_tools.dir/all' failed
make[1]: *** [CMakeFiles/fastllm_tools.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:92: recipe for target 'CMakeFiles/fastllm.dir/all' failed
make[1]: *** [CMakeFiles/fastllm.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by HonglinChu** [comment]
me too

**Comment by TylunasLi** [comment]
请先参考 #64 和 #194

**Comment by Dominicbrian** [comment]
几种解决方法中可以通过以下配置解决，不知道是不是会影响推理速度
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread --std=c++17 -O2")

**Comment by Dominicbrian** [comment]
几种解决方法中可以通过以下配置解决，不知道是不是会影响推理速度，感谢！
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread --std=c++17 -O2")
