### ISSUE TITLE
Unkown model type: internlm

### ISSUE THREAD

**Issue by weicheng59** [ztxz16/fastllm#205]
Following readme, the generated .flm file from internlm cannot inference with this error.

Unkown model type: internlm
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)

Any plan to support InternLM-7B?

**Comment by TylunasLi** [comment]
目前，根据model.cpp里面的定义，仅支持了llama，baichuan，chatglm和moss四种modelType，欢迎开发算子，添加支持的model'Type，并提出pr。

**Comment by ztxz16** [comment]
暂时跑不了internLM模型
