### ISSUE TITLE
首个token时延问题

### ISSUE THREAD

**Issue by rayle01** [ztxz16/fastllm#22]
在V100, cuda 11.8 , gcc 11.3环境下测试生成速度，bs=1, 输入query（prompt+query）长度900+，存在首个token时延长的问题：
1. fastllm:  
     - (1)输入长度 1200, 首个token 3.32s, 其他token 20ms
     - (2)输入长度 1200, 首个token 3.32s, 其他token 20ms
     - (3)...
2. torch
     - (1)输入长度 1200, 首个token 1.56s, 其他token 51ms
     - (2)输入长度 1200, 首个token 0.12s, 其他token 51ms
     - (3)输入长度 1200, 首个token 0.11s, 其他token 51ms
     - (4)...
结果是fastllm的首个token时延随query长度变化很大，且每个query都会有一样的实验，torch会随着query递减。结果长度短的（<50 token）情况下，对比torch没有优势。

**Comment by ztxz16** [comment]
用fp16模型首token基本上没延时，int8模型的我还没弄好.. 估计要等等
主要是因为fp16有cublas的函数可以直接用，int8里面是float * int8 -> float的矩阵乘法，没有现成的加速库

**Comment by rayle01** [comment]
给力，刚提交的代码是不是fp16的首token改错了，又回到2s~3s的水平了。12号拉的代码速度还只有200ms左右

**Comment by ztxz16** [comment]
> 给力，刚提交的代码是不是fp16的首token改错了，又回到2s~3s的水平了。12号拉的代码速度还只有200ms左右

啊，具体是什么模型？ 我刚才测试了一下是正常的，fp16首token我这边基本没延迟

**Comment by rayle01** [comment]
chatglm，拉取的最新的代码转fp16后， 代开src/chatglm.cc的打印每个token时延，出的结果如下（图一）。同样的query在12号速度是可以的（图2）。输入长度1000+
![chatglm-fp16-generate-throughput](https://github.com/ztxz16/fastllm/assets/42346715/d35d2a66-e55e-4310-84a2-c10a6a621b17)
![image](https://github.com/ztxz16/fastllm/assets/42346715/d635c3f0-3af4-4ca0-a26b-6f76ee87a1c7)

**Comment by ztxz16** [comment]
> chatglm，拉取的最新的代码转fp16后， 打开chatglm.cpp中打印每个token时延，出的结果如下（图一）。同样的query在12号速度是可以的（图2）。输入长度1000+ ![chatglm-fp16-generate-throughput](https://user-images.githubusercontent.com/42346715/247372747-d35d2a66-e55e-4310-84a2-c10a6a621b17.PNG) ![image](https://user-images.githubusercontent.com/42346715/247373125-d635c3f0-3af4-4ca0-a26b-6f76ee87a1c7.png)

已修复，谢谢提出

**Comment by rayle01** [comment]
嗯，确认了速度已改过来，给力

**Comment by ray-008** [comment]
> 用fp16模型首token基本上没延时，int8模型的我还没弄好.. 估计要等等 主要是因为fp16有cublas的函数可以直接用，int8里面是float * int8 -> float的矩阵乘法，没有现成的加速库

我用int4后的模型也出现这个问题，当提示词很长的时候，第一个token就会很慢。fp16就很快，目前还没有很好的解决办法是吧？

**Comment by vfdff** [comment]
请问是怎么统计这个耗时 ？
