### ISSUE TITLE
能否用在阿里的qwen-7b上？qwen-7B测试下来，全面碾压ChatGLM2-6B，就是推理速度有点慢

### ISSUE THREAD

**Issue by homelee** [ztxz16/fastllm#223]

**Comment by bh4ffu** [comment]
+1

**Comment by siemonchan** [comment]
已在这个[fork](https://github.com/siemonchan/fastllm.git)中实现，并merge到master

**Comment by homelee** [comment]
我转换了int4模型，但是运行出错
![image](https://github.com/ztxz16/fastllm/assets/3040122/138b461e-d11a-4753-972f-129fd6a22a52)

**Comment by homelee** [comment]
补充一下，去掉-l没有报错了

**Comment by siemonchan** [comment]
> 补充一下，去掉-l没有报错了

这个错误在最新的pr中已经修复了
