### ISSUE TITLE
Got an error "TypeError: Got unsupported ScalarType BFloat16" when convert model to flm

### ISSUE THREAD

**Issue by bigmover** [ztxz16/fastllm#229]
I want to convert  codegeex2 to flm model with chatglm_export.py. But got an error "TypeError: Got unsupported ScalarType BFloat16". What can i do to fix it？
![image](https://github.com/ztxz16/fastllm/assets/26063296/cf8e7680-744e-453e-9ca0-19edd0715638)

**Comment by HuaYZhao** [comment]
我也遇到了这个问题，加一行model = model.half()目前解决了这个问题

**Comment by bigmover** [comment]
> 我也遇到了这个问题，加一行model = model.half()目前解决了这个问题

确实可以。谢谢@HuaYZhao
