### ISSUE TITLE
Python API hang on Windows while loading

### ISSUE THREAD

**Issue by TylunasLi** [ztxz16/fastllm#232]
测试环境：  Windows 10   MSVC 2015 update 3   pybind11 2.8.1   cmake 3.26.5   python 3.6 3.10

Windows下编译Python库后使用Python API，无论是使用fastllm_tools.dll，还是pyfastllm.*.pyd，在import阶段均会卡住。
经过调试，发现均卡死在 [ include / devices / cpu / cputhreadpool.h : 91](https://github.com/ztxz16/fastllm/blob/3f12eab302d53502b9cd327304eb82bd40511dac/include/devices/cpu/cputhreadpool.h#L91C14-L91C14) 处。

![windows下线程池卡死](https://github.com/ztxz16/fastllm/assets/22093949/962c7004-cdd6-4546-8187-70771ee98691)

**Comment by TylunasLi** [comment]
> 这个好奇怪。。 只是新建了一个线程池 是新版本出现的bug吗，直接c++代码可以跑吗？

直接c++代码一切正常。

**Comment by aurxs** [comment]
解决了吗，我好像也遇到了一样的问题

**Comment by wildkid1024** [comment]
建议看下c++版本和python的编译用的版本是否一致。
具体来讲，在终端输入python时会提示gcc版本。

**Comment by TylunasLi** [comment]
> 建议看下c++版本和python的编译用的版本是否一致。 具体来讲，在终端输入python时会提示gcc版本。

Python 3.6.8 基于 MSC v.1916 （Visual Studio 2017 version 15.9）
Python 3.10.8 基于 MSC v.1933 （Visual Studio 2022 version 17.3）

**Comment by TylunasLi** [comment]
@wildkid1024  改编译器后编译，依然挂起。类似这个答案中观察到的现象。

https://stackoverflow.com/questions/42579625/why-does-stdthread-wait-in-its-constructor

**Comment by TylunasLi** [comment]
根据[Common Sources Of GIL Errors](https://pybind11.readthedocs.io/en/stable/advanced/misc.html#common-sources-of-global-interpreter-lock-errors)，虽然线程池不是pybind11 objects，但将线程池修改为懒加载后，Windows下已可以使用。
