### ISSUE TITLE
调用chatlm2-6b原始模型报错KeyError: 'model_type'

### ISSUE THREAD

**Issue by wujingbo-web** [ztxz16/fastllm#237]
今天20230811，克隆了fastllm代码，跑chatglm2-6b生成的flm文件正常。
尝试通过两行代码进行加速的方式跑chatlm2-6B模型。结果报错
 [root@localhost tools]# python3 chatglm_jingbo_demo.py 
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:07<00:00,  1.10s/it]
Traceback (most recent call last):
  File "/data/fastllm/build/tools/chatglm_jingbo_demo.py", line 9, in <module>
    model = llm.from_hf(model, tokenizer, dtype = "float16") # dtype支持 "float16", "int8", "int4"
  File "/data/fastllm/build/tools/fastllm_pytools/llm.py", line 94, in from_hf
    return hf_model.create(model, tokenizer, dtype = dtype);
  File "/data/fastllm/build/tools/fastllm_pytools/hf_model.py", line 38, in create
    if (modelInfo["model_type"] == "baichuan" and hasattr(model, "model") and hasattr(model.model, "get_alibi_mask")):
KeyError: 'model_type'

--------------- 下面是我写的demo代码，去调原始的chatglm2-6b ----------
[root@localhost tools]# cat chatglm_jingbo_demo.py 
# 这是原来的程序，通过huggingface接口创建模型
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("/data/wenda/model/chatglm2-6b", trust_remote_code = True)
model = AutoModel.from_pretrained("/data/wenda/model/chatglm2-6b", trust_remote_code = True)
# 加入下面这两行，将huggingface模型转换成fastllm模型
# 目前from_hf接口只能接受原始模型，或者ChatGLM的int4, int8量化模型，暂时不能转换其它量化模型

from fastllm_pytools import llm
model = llm.from_hf(model, tokenizer, dtype = "float16") # dtype支持 "float16", "int8", "int4"
model = model.eval()

# 生成回复
print(model.response("请介绍下你自己，并且生成100以内的素数如何实现？"))

# 流式生成回复
for response in model.stream_response("你好"):
    print(response, flush = True, end = "")

**Comment by ztxz16** [comment]
需要更新一下chatglm2-6b模型（至少更新config.json文件），这个问题是开始的模型里没指定model_type，识别不出模型类型
