### ISSUE TITLE
关于量化的细节

### ISSUE THREAD

**Issue by irasin** [ztxz16/fastllm#24]
请问下关于linear层的int8和int4的量化策略是怎样的呢？以及推理时是还原成fp16再计算的吗

**Comment by ztxz16** [comment]
量化策略是用的tflite的非对称量化
CUDA推理时会用fp32精度计算

**Comment by irasin** [comment]
@ztxz16，感谢回复
我刚才看了一下代码，量化的部分提到了 Linear层权重，分通道量化之

请问这个分通道是指的per-channel量化吗，还是说有什么特殊的分法？

**Comment by ztxz16** [comment]
是的，目前就是per-channel

**Comment by irasin** [comment]
感谢！
