### ISSUE TITLE
加载模型时出现bug

### ISSUE THREAD

**Issue by wildkid1024** [ztxz16/fastllm#25]
FastLLM Error: FileBuffer.ReadInt error.

terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
已放弃

**Comment by wildkid1024** [comment]
一般是文件格式不对，我跑的时候傻逼了。

**Comment by ArtificialZeng** [comment]
> 一般是文件格式不对，我跑的时候傻逼了。

怎么搞

**Comment by renllll** [comment]
请问现在解决这个问题了吗，我也遇到了

**Comment by yijiejiang** [comment]
现在我也遇到了这个问题
