### ISSUE TITLE
chatglm2-6b+fastllm，推理时报错'NoneType' object has no attribute 'stream_chat'

### ISSUE THREAD

**Issue by azhe12** [ztxz16/fastllm#251]
chatglm-6b + fastllm，推理时，报错。

# 修改web_demo.py
添加2行fastllm支持
<img width="1208" alt="image" src="https://github.com/ztxz16/fastllm/assets/5035731/978418a7-0812-4bae-b73c-6546bd5fd904">

启动正常，python web_demo.py

但是，在网页上提问后，网页没反应，看服务端已经报错。
<img width="1241" alt="image" src="https://github.com/ztxz16/fastllm/assets/5035731/ebdb3426-e418-4a36-b67d-c96013aca5e5">

# web_demo.py错误如下：
AttributeError: 'NoneType' object has no attribute 'stream_chat'

![5131d3eb60bf7c8848be0e7b0a4ce9b8](https://github.com/ztxz16/fastllm/assets/5035731/5c9f1195-9e29-4e16-8ea8-1ba2254de313)

**Comment by lhzwangwei** [comment]
model.eval 关了

**Comment by azhe12** [comment]
yi已验证，问题修复。专业，靠谱。

方法：注释掉model = model.eval()

![image](https://github.com/ztxz16/fastllm/assets/5035731/deb89862-d127-4bc2-9b30-9c3998b6d88b)


> model.eval 关了
