### ISSUE TITLE
最新版GPU编译后，使用fastllm_pytools直接加载flm模型会报错，status=7

### ISSUE THREAD

**Issue by ResultLv** [ztxz16/fastllm#252]
问题描述：
GPU：V100，显存32G，加载报错时显存足够
最新版GPU编译后，使用fastllm_pytools直接加载flm模型会报错，status=7
![image](https://github.com/ztxz16/fastllm/assets/34031240/685042aa-f7b9-4031-bbc0-a409722192d5)

但在加载原始模型后，再加载flm模型就能正常加载和推理
![image](https://github.com/ztxz16/fastllm/assets/34031240/8f95f949-07a2-4546-afec-b5dd8f08ac97)

**Comment by TylunasLi** [comment]
status 7 意为 CUBLAS_STATUS_INVALID_VALUE
