### ISSUE TITLE
QWen量化到int8保存文件大小 9.0G 正常吗？

### ISSUE THREAD

**Issue by BenRood8165290** [ztxz16/fastllm#253]
就是感觉有点奇怪，推理正常，加载后显存占用也只是是 7.7G，原始bin总大小是15G。

对比ChatGLM2-6b：
原始bin总大小12G，量化到int8保存是6.6G。

**Comment by ztxz16** [comment]
正常的，这个模型词表Embedding部分很大，所以转出来大一点
这部分不会存在显存里，所以显存占用没有这么大
如果用low_mem模式运行的话，这部分也不会进到内存里
