### ISSUE TITLE
2080ti22G下与vllm性能对比

### ISSUE THREAD

**Issue by HelloCard** [ztxz16/fastllm#263]
使用wsl2中的ubyntu22.04，显卡是2080ti22G，分别在vllm和fastllm上进行benchmark。
这是vllm的表现：
Avg prompt throughput: 1259.0 tokens/s, Avg generation throughput: 206.1 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 54 reqs, GPU KV cache usage: 97.8%, CPU KV cache usage: 0.0%
这是fastllm，batch再高就报cublas error了，~/fastllm/build# ./benchmark -p /mnt/e/Code/Text-Generation-WebUI/models/huangyuyang_Qwen-7B-Chat-fp16.flm/Qwen-7B-Chat-fp16.flm  -f ../example/benchmark/prompts/hello.txt -b 13 -l 128：
batch: 13
prompt token number = 2207
prompt use 0.590404 s
prompt speed = 3738.118408 tokens / s
output 889 tokens
use 5.107274 s
speed = 174.065460 tokens / s
测试所用的输入提取自ShareGPT_V3_unfiltered_cleaned_split.json，速度相差不大，此外我看了benchmark.cpp的代码，逻辑是按照batch从hello.txt里取条目，取到的条目一口气塞给模型推理，感觉写得太随意了，像这个测试结果，13行输入一口气塞进去5秒就测完了，远不如按照batch从hello.txt的上千行里逐次取条目，跑上二十分钟取平均值。

**Comment by ztxz16** [comment]
我最近也在写一个api_server，之后应该也会按vllm的方式测一下
话说VLLM的这个结果是用什么测试的

**Comment by HelloCard** [comment]
在第一个wsl终端里安装vllm之后用项目里的 wget https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered/resolve/main/ShareGPT_V3_unfiltered_cleaned_split.json 命令下载ShareGPT_V3_unfiltered_cleaned_split.json到\\wsl.localhost\Ubuntu-22.04\root\vllm\benchmarks目录下。
在第二个wsl终端里的vllm目录下用 python -m vllm.entrypoints.api_server --model /mnt/e/Code/Text-Generation-WebUI/models/Qwen_Qwen-7B-Chat --trust-remote-code 启动服务端。
最后在第一个wsl终端里用python benchmark_serving.py --backend vllm --tokenizer Qwen/Qwen-7B-Chat --dataset ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 2000 --request-rate 4 --host 127.0.0.1 --port 8000 --trust-remote-code 指令进行跑分，实际上有一些故障，跑到后面以后服务端会在convert_id_to_token时因为unknown ids而报错，然后第一个wsl终端里的benchmark脚本会中断，但是服务端每隔一些请求都会进行一次性能输出，这些是崩溃前的输出：
INFO 08-18 20:45:21 llm_engine.py:394] Avg prompt throughput: 268.0 tokens/s, Avg generation throughput: 335.3 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 437 reqs, GPU KV cache usage: 95.1%, CPU KV cache usage: 0.0%
INFO 08-18 20:45:26 llm_engine.py:394] Avg prompt throughput: 528.1 tokens/s, Avg generation throughput: 290.5 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 447 reqs, GPU KV cache usage: 83.4%, CPU KV cache usage: 0.0%
INFO 08-18 20:45:31 llm_engine.py:394] Avg prompt throughput: 476.1 tokens/s, Avg generation throughput: 274.6 tokens/s, Running: 11 reqs, Swapped: 0 reqs, Pending: 468 reqs, GPU KV cache usage: 82.6%, CPU KV cache usage: 0.0%
INFO 08-18 20:45:36 llm_engine.py:394] Avg prompt throughput: 511.8 tokens/s, Avg generation throughput: 316.9 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 473 reqs, GPU KV cache usage: 95.4%, CPU KV cache usage: 0.0%
INFO 08-18 20:45:41 llm_engine.py:394] Avg prompt throughput: 710.8 tokens/s, Avg generation throughput: 250.0 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 486 reqs, GPU KV cache usage: 92.6%, CPU KV cache usage: 0.0%
INFO 08-18 20:45:46 llm_engine.py:394] Avg prompt throughput: 1125.2 tokens/s, Avg generation throughput: 288.2 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 499 reqs, GPU KV cache usage: 92.4%, CPU KV cache usage: 0.0%
INFO 08-18 20:45:51 llm_engine.py:394] Avg prompt throughput: 452.1 tokens/s, Avg generation throughput: 343.2 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 513 reqs, GPU KV cache usage: 94.8%, CPU KV cache usage: 0.0%
INFO 08-18 20:45:56 llm_engine.py:394] Avg prompt throughput: 705.2 tokens/s, Avg generation throughput: 321.9 tokens/s, Running: 23 reqs, Swapped: 0 reqs, Pending: 516 reqs, GPU KV cache usage: 89.1%, CPU KV cache usage: 0.0%
INFO 08-18 20:46:01 llm_engine.py:394] Avg prompt throughput: 817.9 tokens/s, Avg generation throughput: 387.2 tokens/s, Running: 37 reqs, Swapped: 0 reqs, Pending: 506 reqs, GPU KV cache usage: 98.1%, CPU KV cache usage: 0.0%
INFO 08-18 20:46:06 llm_engine.py:394] Avg prompt throughput: 179.6 tokens/s, Avg generation throughput: 506.6 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 532 reqs, GPU KV cache usage: 97.3%, CPU KV cache usage: 0.0%
INFO 08-18 20:46:11 llm_engine.py:394] Avg prompt throughput: 366.7 tokens/s, Avg generation throughput: 380.9 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 551 reqs, GPU KV cache usage: 98.4%, CPU KV cache usage: 0.0%
INFO 08-18 20:46:16 llm_engine.py:394] Avg prompt throughput: 470.0 tokens/s, Avg generation throughput: 324.6 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 571 reqs, GPU KV cache usage: 97.0%, CPU KV cache usage: 0.0%
INFO 08-18 20:46:21 llm_engine.py:394] Avg prompt throughput: 297.8 tokens/s, Avg generation throughput: 313.7 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 591 reqs, GPU KV cache usage: 99.2%, CPU KV cache usage: 0.0%
INFO 08-18 20:46:26 llm_engine.py:394] Avg prompt throughput: 593.7 tokens/s, Avg generation throughput: 281.0 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 592 reqs, GPU KV cache usage: 92.1%, CPU KV cache usage: 0.0%
INFO 08-18 20:46:31 llm_engine.py:394] Avg prompt throughput: 851.9 tokens/s, Avg generation throughput: 266.6 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 597 reqs, GPU KV cache usage: 97.8%, CPU KV cache usage: 0.0%
INFO 08-18 20:46:36 llm_engine.py:394] Avg prompt throughput: 769.8 tokens/s, Avg generation throughput: 285.8 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 608 reqs, GPU KV cache usage: 98.1%, CPU KV cache usage: 0.0%
INFO 08-18 20:46:41 llm_engine.py:394] Avg prompt throughput: 636.7 tokens/s, Avg generation throughput: 284.3 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 622 reqs, GPU KV cache usage: 97.0%, CPU KV cache usage: 0.0%
INFO 08-18 20:46:46 llm_engine.py:394] Avg prompt throughput: 594.8 tokens/s, Avg generation throughput: 229.4 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 645 reqs, GPU KV cache usage: 97.3%, CPU KV cache usage: 0.0%
我说vllm的效率是200token/s是为了稳妥起见取的最小值。
