### ISSUE TITLE
当前版本win32demo 编译出错

### ISSUE THREAD

**Issue by BoFan-tunning** [ztxz16/fastllm#281]
![U~7MJ@8(FK%M3)@)BD RO6](https://github.com/ztxz16/fastllm/assets/129488076/305e626e-8eff-406c-90bc-5d2e23a96fab)

**Comment by TylunasLi** [comment]
已提交pull request #282

**Comment by BoFan-tunning** [comment]
感谢，开发者[TylunasLi)的，及时解决
