### ISSUE TITLE
回答很多个感叹号和其他字符

### ISSUE THREAD

**Issue by ARES3366** [ztxz16/fastllm#318]
"......!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv surv ......"

对Qwen-7b-Chat的模型进行转换后，问什么都是很多上面的字符，请问下这是咋回事？
cuda11.8，A100

同事在V100 上，cuda118是可以加速跑通的

**Comment by TylunasLi** [comment]
你和同事使用的是同样的文件吗？
如果是微调过的模型，看下原版模型是否有同样的问题？

**Comment by ztxz16** [comment]
同样模型在别的机器上可以跑通的话，一般可能是编译有点问题，可以试着把CMakeLists.txt里的CMAKE_CUDA_ARCHITECTURES改一下（改成A100对应的计算力）

**Comment by ARES3366** [comment]
已经可以了，很感谢
其实已经不知道改了什么，最终成功了

**Comment by ARES3366** [comment]
改了CMakeLists.txt里的CMAKE_CUDA_ARCHITECTURES A100算力，也改了flash-attn和另外两三个库的版本
