### ISSUE TITLE
pytools 中 string_to_chars 相关的内存泄漏

### ISSUE THREAD

**Issue by lockmatrix** [ztxz16/fastllm#326]
从C++侧，通过函数返回值返回 `string_to_chars` 产生的 `char*` 到python中后并没有释放，会导致内存泄漏。

建议方式：
方案1：
* 在C++侧增加一个 `free_str` 函数，python侧使用完之后，调用该函数进行释放。（该内存是由C++侧的内存分配器申请的，只能在C++侧释放）

方案2：
* 在python侧通过函数参数传入一个足够大的可写buffer，C++侧直接把结果写入该块内存中。

**Comment by ztxz16** [comment]
相关PR已经merge

**Comment by lockmatrix** [comment]
> 相关PR已经merge

#328 只是新增了一个接口，原有接口的泄露问题仍然存在
