### ISSUE TITLE
support the tokp topk  and penalty logic

### ISSUE THREAD

**Issue by junior-zsy** [ztxz16/fastllm#34]
The current code lacks support for the tokp topk penalty mechanism. I kindly request you to consider adding it. Thank you.

**Comment by ztxz16** [comment]
I'll add it as soon as possible, probably this week

**Comment by Vincent131499** [comment]
Is this supported?

**Comment by yuto3o** [comment]
same as #59

**Comment by ztxz16** [comment]
新版本已经支持了
