### ISSUE TITLE
是否考虑支持baichuan2-7B的RoPE编码？

### ISSUE THREAD

**Issue by 91he** [ztxz16/fastllm#342]
baichuan2的7B模型和13B模型采用了不同的位置编码方式，目前fastllm仅支持baichuan2-13B的模型，接下来是否考虑增加对7B模型和RoPE的支持？

**Comment by TylunasLi** [comment]
baichuan-2-7B的位置编码应该是和baichuan1-7b以及llama是一致的。fastllm应该早就支持了，如果在支持方面遇到具体问题，希望能反馈具体的问题。

**Comment by 91he** [comment]
> baichuan-2-7B的位置编码应该是和baichuan1-7b以及llama是一致的。fastllm应该早就支持了，如果在支持方面遇到具体问题，希望能反馈具体的问题。

但是实际情况是baichuan2在模型转换时是通过检测abili属性来判断模型的版本，7B的模型显然没有这个property。而且我反复尝试过转换7B的模型，始终没有得到过正确的输出。

**Comment by 91he** [comment]
@TylunasLi 我想 [#317](https://github.com/ztxz16/fastllm/issues/317) 的问题已经提出很久了，一定不只有我一个人在使用baichuan2-7B模型时遇到了问题。
