### ISSUE TITLE
道歉贴：我因为fork了此项目，被人一直辱骂和骚扰。致此向原作者道歉。

### ISSUE THREAD

**Issue by ArtificialZeng** [ztxz16/fastllm#373]
因为fork了此项目，分享到微信群里。长期被人辱骂。 我只是想传播和转发。 
这个项目开启了，谁都知道谁是原作者。 我只是尝试了代码解释和分享博文相关的部分。

从来不会以原作者自居。

希望你们停歇吧。

![image](https://github.com/ztxz16/fastllm/assets/39647839/dc1b11a7-17b5-499f-9e46-32e36da6acd3)

**Comment by shijunbao** [comment]
别讨论这些非技术问题。。。

**Comment by ArtificialZeng** [comment]
> 别讨论这些非技术问题。。。

谢谢，是我的错。
