### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by wenweichan** [ztxz16/fastllm#375]
python3 tools/cli_demo.py -p chatglm2-6b-int4.flm按教程部署完之后运行会报“Floating point exception”的错误
![Uploading 屏幕截图 2023-11-23 155109.png…]()

**Comment by RayenAlex** [comment]
我也遇到这个问题，自己转换模型是会出现这个问题，下载转换好的https://huggingface.co/huangyuyang/chatglm-6b-int4.flm 就不会报这个错

**Comment by hebangwen** [comment]
这个问题是因为 `CPUDevice::Run` 需要从 int_param 中拿出 `q___batch`，而 `q___batch` 没有设置，会变成默认值 0，导致 divide by zero 错误。解决方法：在 `fastllm::Attention` 函数中添加 `q___batch`，如下：

``` c++
    void Attention(const Data &q, const Data &k, const Data &v, const Data &mask, Data &output,
                   int group, float scale, int attentionType) {
        curExecutor->Run("Attention", {
                {"q", (Data*)&q}, {"k", (Data*)&k}, {"v", (Data*)&v},
                {"mask", (Data*)&mask}, {"output", (Data*)&output}
        }, {{"scale", scale}}, {{"group", group}, {"q___batch", 1}});
    }


```
