### ISSUE TITLE
tokenizer对不齐

### ISSUE THREAD

**Issue by eigen2017** [ztxz16/fastllm#380]
输入[Round1]

google sp tokenizer load token.model之后，分词结果：
_[                R                ound     
790            30951            517

fastllm自带分词结果：
[     Ro  und  

看到fastllm已经集成google sp，但是延迟上对于长一点的prompt要100ms，期待有性能+对齐的改进。

**Comment by TylunasLi** [comment]
文本中有空格的地方存在对不齐的情况：

文本：`\n  \\n问题：怎么向目标客户介绍公司？` （中间有2个空格）

fastlllm

    64795 13 30974 30916 7253   30916 31639 31211 ...
             “\” “n” “▁\\” “问题”“：”

sentencepiece

    64795 13 701 30916 265 6281 30916 31639 31211 ...
             “▁\” “n” “▁▁” “\\” “问题” “：”

**Comment by eigen2017** [comment]
thks
