### ISSUE TITLE
用root用户cmake 和 make 之后，用应用用户"ai"进行python setup.py install 报权限不足

### ISSUE THREAD

**Issue by xinaiwunai** [ztxz16/fastllm#382]
使用root用户(python 2.7) cmake 和 make 。
使用应用用户"ai"(anaconda base python 3.11 )
执行 python setup.py install 
报error: could not create 'fastllm_pytools.egg-info': Permission denied

如果sudo 执行，则会报部分py脚本的invalid syntax错误

**Comment by TylunasLi** [comment]
1. 检查build路径的权限，“ai”用户是否有写权限；
2. 执行编译的时候尽量使用与安装相同的python环境和版本。

以上问题并非本项目的问题。

**Comment by xinaiwunai** [comment]
thanks. 我最后选择了全部使用root用户，解决了这个问题。
