### ISSUE TITLE
能否提供一下非网盘的下载方式

### ISSUE THREAD

**Issue by wangzhaode** [ztxz16/fastllm#4]
rt

**Comment by ztxz16** [comment]
大佬有什么推荐吗.. 我手头没有服务器暂时只能传网盘

**Comment by wangzhaode** [comment]
huggingface网速比较快；或者发布到github release里也行

**Comment by wangzhaode** [comment]
我先试用用你提供的脚本导出了

**Comment by ztxz16** [comment]
> huggingface下载的速度比较快；或者发布到github release里也行

gtihub assets我空间不够.. 我后面学习下huggingface上传

**Comment by wangzhaode** [comment]
好的 多谢

**Comment by wangzhaode** [comment]
另外chatglm好像不支持上下文，把前面的历史信息作为下一次的输入就可以了

**Comment by wangzhaode** [comment]
用户: 晚上睡不着怎么办
ChatGLM:  以下是一些可能有助于改善晚上睡不着的方法:

1. 建立规律的睡眠时间:尽量在同一时间上床睡觉,并尽量在早上同一时间起床。

2. 创造舒适的睡眠环境:保持房间安静、凉爽、黑暗、舒适,并使用舒适的床垫和枕头。

3. 放松身体和思维:使用深呼吸、渐进性肌肉松弛、冥想或瑜伽等方法放松身体和思维。

4. 避免刺激性物质:避免饮用咖啡、茶、可乐等刺激性饮料,并避免吸烟和饮酒。

5. 避免在床上使用电子设备:避免在床上使用电子设备,如手机、电脑、平板等,这些设备会发出蓝光,干扰身体分泌褪黑素,导致难以入睡。

6. 尝试一些放松技巧:尝试一些放松技巧,如渐进性肌肉松弛、冥想、瑜伽等,帮助放松身体和思维。

7. 寻求专业帮助:如果以上方法无法改善睡眠,建议寻求专业帮助,如咨询医生或睡眠专家。
用户: 还有吗
ChatGLM:  很抱歉,我不太明白您的问题是什么。您可以请提供更多背景信息或详细说明您的问题吗?这样我就可以更好地回答您的问题。

**Comment by ztxz16** [comment]
> 用户: 晚上睡不着怎么办 ChatGLM: 以下是一些可能有助于改善晚上睡不着的方法:
> 
> 1. 建立规律的睡眠时间:尽量在同一时间上床睡觉,并尽量在早上同一时间起床。
> 2. 创造舒适的睡眠环境:保持房间安静、凉爽、黑暗、舒适,并使用舒适的床垫和枕头。
> 3. 放松身体和思维:使用深呼吸、渐进性肌肉松弛、冥想或瑜伽等方法放松身体和思维。
> 4. 避免刺激性物质:避免饮用咖啡、茶、可乐等刺激性饮料,并避免吸烟和饮酒。
> 5. 避免在床上使用电子设备:避免在床上使用电子设备,如手机、电脑、平板等,这些设备会发出蓝光,干扰身体分泌褪黑素,导致难以入睡。
> 6. 尝试一些放松技巧:尝试一些放松技巧,如渐进性肌肉松弛、冥想、瑜伽等,帮助放松身体和思维。
> 7. 寻求专业帮助:如果以上方法无法改善睡眠,建议寻求专业帮助,如咨询医生或睡眠专家。
>    用户: 还有吗
>    ChatGLM:  很抱歉,我不太明白您的问题是什么。您可以请提供更多背景信息或详细说明您的问题吗?这样我就可以更好地回答您的问题。

嗯... 之前是因为上下文多了速度过于慢了，所以没加上下文；不过这部分优化过了，后面main程序里面我改一下

**Comment by wangzhaode** [comment]
ok 我改了一下

**Comment by wangzhaode** [comment]
https://github.com/ztxz16/fastllm/pull/5

**Comment by wangzhaode** [comment]
测试了一下 Android上速度很不错 小米12上平均能达到 1 tok/s 左右的速度

**Comment by wangzhaode** [comment]
ARMv8.2使用fp16
ARMv8.6使用bf16
替代fp32做Linear速度会更快一些

**Comment by wangzhaode** [comment]
![image](https://github.com/ztxz16/fastllm/assets/8401806/803c03f6-c0fb-4845-98a1-dab04d3ea559)

如果可以进这个群里来讨论一下；群里有很多希望在端侧部署ChatGLM的开发者

**Comment by ztxz16** [comment]
> 测试了一下 Android上速度很不错 小米12上平均能达到 1 tok/s 左右的速度

这个是哪个模型.. 我这边测试用的小米10pro测试ChatGLM-6b-int4/8大概300ms一个token，小米12应该不止这个速度吧

**Comment by ztxz16** [comment]
> ![image](https://user-images.githubusercontent.com/8401806/238557999-803c03f6-c0fb-4845-98a1-dab04d3ea559.png)
> 
> 如果可以进这个群里来讨论一下；群里有很多希望在端侧部署ChatGLM的开发者

好的我加了

**Comment by wangzhaode** [comment]
> > 测试了一下 Android上速度很不错 小米12上平均能达到 1 tok/s 左右的速度
> 
> 这个是哪个模型.. 我这边测试用的小米10pro测试ChatGLM-6b-int4/8大概300ms一个token，小米12应该不止这个速度吧

int4的模型

**Comment by rayle01** [comment]
@ztxz16 二维码过期了

**Comment by GalSang17** [comment]
@ztxz16 二维码过期了，可以更新一下吗，现在都用wechat，qq基本不看

**Comment by ztxz16** [comment]
> @ztxz16 二维码过期了，可以更新一下吗，现在都用wechat，qq基本不看

![image](https://github.com/ztxz16/fastllm/assets/13409660/ce2abbec-86e4-441b-84ca-0a157dc0ffbd)
这个群主要是讨论chatglm部署的，是mnn大佬的群

**Comment by ztxz16** [comment]
以后计划发布到https://huggingface.co/huangyuyang

**Comment by 598753468** [comment]
再传个网盘呗，为了下你的模型刚开的会员😭

**Comment by ztxz16** [comment]
链接：https://pan.baidu.com/s/10KDRuna8zK91xdPv0Zyvfw 
提取码：2joc

**Comment by ray-008** [comment]
> > @ztxz16 二维码过期了，可以更新一下吗，现在都用wechat，qq基本不看
> 
> ![image](https://user-images.githubusercontent.com/13409660/246371949-ce2abbec-86e4-441b-84ca-0a157dc0ffbd.png) 这个群主要是讨论chatglm部署的，是mnn大佬的群

重新给个二维码吧，过期了
