### ISSUE TITLE
pybind 在模型解码出非 Unicode 字符，传给 callback 时报错

### ISSUE THREAD

**Issue by Arrivederci** [ztxz16/fastllm#41]
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte`

使用 python 时建议将此处的 callback 参数从字符串改为 py::bytes，在 python 代码中 decode
https://github.com/ztxz16/fastllm/blob/master/include/models/basellm.h#L4

参考
https://pybind11.readthedocs.io/en/stable/advanced/cast/strings.html

**Comment by cgisky1980** [comment]
decode 的时候 带上replace参数

**Comment by kiranosora** [comment]
最新主分支已修复此问题
