### ISSUE TITLE
Error: cublas error during MatMul in Attention operator.

### ISSUE THREAD

**Issue by pingyuan2016** [ztxz16/fastllm#433]
![image](https://github.com/ztxz16/fastllm/assets/25808622/d8d60c3c-1de0-4767-bd65-4f12b960ca1a)
操作步骤：
1、使用chatglm3进行，微调
2、我这有两个显卡，使用cuda:0进行合并，调用的时候，使用cuda:1调用合并之后的模型，报上图错误

Error: CUDA error when allocating 8236 kB memory! maybe there's no enough memory left on device.
  CUDA error = 2, cudaErrorMemoryAllocation at /home/duanjinqiang/project/llm/fastllm/src/devices/cuda/fastllm-cuda.cu:1485
  'out of memory'
status = 7
Error: cublas error during MatMul in Attention operator.
terminate called after throwing an instance of 'char const*'
Aborted

**Comment by TylunasLi** [comment]
这个提示很明显是显存不足了。您需要关注在报错的那个时刻，显存的分配情况是怎么样的。
如果设置过了`set_device_map()`，但显存仍然没有分配到您希望的GPU上，可以：
1. 设置如下环境变量
```shell
export CUDA_DEVICE_ORDER=PCI_BUS_ID
```
2. 检查环境变量`CUDA_VISIBLE_DEVICES`是否正确，如果锁定了0号卡，则执行`set_device_map(“cuda:1”)`还是0号卡。

**Comment by pingyuan2016** [comment]
3q，看到了，有个显卡显存被占用了，但是没有显示占用的程序，以为是空卡，关了

**Comment by pingyuan2016** [comment]
1

**Comment by pingyuan2016** [comment]
1
