### ISSUE TITLE
中文输入无法识别；webui打开的地址无法访问。

### ISSUE THREAD

**Issue by Mihubaba** [ztxz16/fastllm#447]
1、中文输入输出乱码；
![image](https://github.com/ztxz16/fastllm/assets/156389411/9b813a4e-25da-4d6d-a9a8-5de19ed1e75d)
我在别的issue看到main函数添加system("chcp 65001")，具体怎么实现呢？
2、webui打开的地址无法访问；
(chatglm3) D:\Python\C or C++ project\fastllm\build-GPU\Debug>webui.exe -p chatglm3-6b-fp16.flm --port 8000
Load (200 / 200) 
Warmup...
finish.
>>> please open http://127.0.0.1:8000
浏览器打开这个地址无法访问。

**Comment by TylunasLi** [comment]
> 1、Windows中文输入乱码

见 [FAQ](https://github.com/ztxz16/fastllm/blob/master/docs/faq.md#mainexe-%E6%97%A0%E6%B3%95%E8%AF%86%E5%88%AB%E4%B8%AD%E6%96%87%E8%BE%93%E5%85%A5)

> 2、webui打开的地址无法访问；

需要制定 -w 参数。指向页面目录。
`webui.exe -p chatglm3-6b-fp16.flm --port 8000 -w ../web/ `
