### ISSUE TITLE
可否改用 huggingface 共享模型，百度云实在太......

### ISSUE THREAD

**Issue by rtgiskard** [ztxz16/fastllm#45]

**Comment by lightrabbit** [comment]
huggingface共享的模型直接用[这个方法](https://github.com/ztxz16/fastllm#chatglm%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA)就可以导出了。

**Comment by rtgiskard** [comment]
> huggingface共享的模型直接用[这个方法](https://github.com/ztxz16/fastllm#chatglm%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA)就可以导出了。

确实可以自己获取原始模型，然后再使用这个工具进行导出，就想llama.cpp一样，不过原始模型大多很大很大，而自行导出也有内存要求。看到readme有提供量化后的模型，这个确实方便很多，就是现在这量化后的模型分享链接是百度云，这个完全可以用huggingface分享模型文件，百度云简直就是噩梦…

**Comment by ztxz16** [comment]
https://huggingface.co/huangyuyang/
这里面有一些转好的模型

**Comment by rtgiskard** [comment]
> https://huggingface.co/huangyuyang/ 这里面有一些转好的模型
如果说全部都想要，会不会显得太贪心😅

其实这个问题的一个侧重点是，为什么要在充当门面的 readme 里放百度云这种链接，huggingface 不香吗 🤤

**Comment by ztxz16** [comment]
> > https://huggingface.co/huangyuyang/ 这里面有一些转好的模型
> 
> 如果说全部都想要，会不会显得太贪心😅
> 
> 其实这个问题的一个侧重点是，为什么要在充当门面的 readme 里放百度云这种链接，huggingface 不香吗 🤤

主要原因是readme好久没更新了。。。 我找时间更新一下

**Comment by zyuerugou** [comment]
huggingface好像被墙了。。。

**Comment by rtgiskard** [comment]
> huggingface好像被墙了。。。

我天朝威武！感觉吃错东西，有点想吐
