### ISSUE TITLE
请问什么时候支持GLM-4 ？

### ISSUE THREAD

**Issue by Stupid-Ai** [ztxz16/fastllm#462]

**Comment by ztxz16** [comment]
已经支持了，目前是直接读hf模型的(./main -p "hf文件夹目录")，文档之后会更新一下

**Comment by Stupid-Ai** [comment]
![image](https://github.com/ztxz16/fastllm/assets/68452058/9dd786cd-9d42-42a5-9ab6-8e8d9a0693c2)
感谢回复，这是cpp的执行方法吗？我只会python，我更新了最新的项目库。但是不管是根据以上代码还是chatglm_export.py都会报这个错误。

**Comment by ztxz16** [comment]
> ![image](https://private-user-images.githubusercontent.com/68452058/337491401-9dd786cd-9d42-42a5-9ab6-8e8d9a0693c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MjQ0NDEsIm5iZiI6MTcxNzcyNDE0MSwicGF0aCI6Ii82ODQ1MjA1OC8zMzc0OTE0MDEtOWRkNzg2Y2QtOWQ0Mi00MmE1LTlhYjYtOGU4ZDlhMDY5M2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDAxMzU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MDRhNDNhZWU5MTY5MWRhZWM5OTE1ZGQwNTg2MzgwOGQyODQ1MmYwNDViYzY5ZmM2MmMzNGU1MGIyMmZjY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VrRZNdMINl4GaUaGIPhLi9WWUVQWR5pdb5HP5uSREXI) 感谢回复，这是cpp的执行方法吗？我只会python，我更新了最新的项目库。但是不管是根据以上代码还是chatglm_export.py都会报这个错误。

现在是
model = llm.model("/home/jupyter-szl/glm-4-9b-chat", dtype = "fp16")
这样执行，上面那个hf模型不用创建了

**Comment by Stupid-Ai** [comment]
可以了，感谢大佬
