### ISSUE TITLE
GLM-4-6B-Chat转换成flm格式后不能加载

### ISSUE THREAD

**Issue by HofNature** [ztxz16/fastllm#465]
使用model.save("model.flm")保存之后
无论是用llm.model("model.flm")加载
还是用main -p model.flm
都提示这个错误：
FastLLM Error: Unkown model type: "chatglm" 
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'

**Comment by ztxz16** [comment]
后面会更新下文档，这个模型目前是直接读取的
./main -p "hf文件夹目录"
python里是model = llm.model("hf文件夹目录")

**Comment by ztxz16** [comment]
后面会更新下文档，这个模型目前是直接读取的
./main -p "hf文件夹目录"
python里是model = llm.model("hf文件夹目录")

**Comment by HofNature** [comment]
谢谢回复，也就是暂时不再支持到Flm格式的转换了是吗？

**Comment by ztxz16** [comment]
> 谢谢回复，也就是暂时不再支持到Flm格式的转换了是吗？

恩，直接读应该更方便吧
以后应该可以让直接读的模型可以导出，相当于之前的转模型了

**Comment by HofNature** [comment]
谢谢您的解答
