### ISSUE TITLE
能否跟自己的python代码结合？

### ISSUE THREAD

**Issue by wjy3326** [ztxz16/fastllm#48]
能否模型加载使用fastllm，然后与自己的python的代码逻辑结合在一起？怎么结合和运行呢？

**Comment by kiranosora** [comment]
可以的，需要先在thirdpary下克隆pybind
然后回主目录编译：
mkdir build-py
cd build-py
cmake .. -DUSE_CUDA=ON -DPY_API=ON
make -j
cd -
python cli.py -m chatglm -p chatglm-6b-int8.bin

**Comment by ztxz16** [comment]
现在已经支持了
