### ISSUE TITLE
ModuleNotFoundError: No module named 'ftllm'

### ISSUE THREAD

**Issue by mingyue0094** [ztxz16/fastllm#492]
```
In [1]: from ftllm import llm
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from ftllm import llm

ModuleNotFoundError: No module named 'ftllm'

In [2]:

In [2]: pip install ftllm
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement ftllm (from versions: none)
ERROR: No matching distribution found for ftllm
Note: you may need to restart the kernel to use updated packages.

In [3]:



```
---

ftllm 模块要通过什么方式安装？

**Comment by ztxz16** [comment]
> ```
> In [1]: from ftllm import llm
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> Cell In[1], line 1
> ----> 1 from ftllm import llm
> 
> ModuleNotFoundError: No module named 'ftllm'
> 
> In [2]:
> 
> In [2]: pip install ftllm
> Looking in indexes: https://mirrors.aliyun.com/pypi/simple
> ERROR: Could not find a version that satisfies the requirement ftllm (from versions: none)
> ERROR: No matching distribution found for ftllm
> Note: you may need to restart the kernel to use updated packages.
> 
> In [3]:
> ```
> 
> ftllm 模块要通过什么方式安装？

暂时只能通过代码安装（clone之后install.sh, 参见主页说明）
