### ISSUE TITLE
quant 方法

### ISSUE THREAD

**Issue by JianbangZ** [ztxz16/fastllm#56]
请问是否有计划实现类似ggml采取更加灵活的量化方法，如Q4_1, q3_k_m

**Comment by wildkid1024** [comment]
这个意思是不同layer使用不同bit的量化吗？

**Comment by JianbangZ** [comment]
> 这个意思是不同layer使用不同bit的量化吗？

对，差不多上是如此

**Comment by ztxz16** [comment]
短期估计不会支持了.. 目前除了Linear层之外，其余层都是FP32的
