### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by neverstoplearn** [ztxz16/fastllm#68]
(pytorch1.13) user@user:~/zx/ChatGLM2-6B$ CUDA_VISIBLE_DEVICES=3 python api_jiasu.py -p ./model.flm
llm model: chatglm
Load (200 / 200) 
Warmup...
Segmentation fault (core dumped)

模型导出成功，导出后加载时报错

**Comment by zhaoying9105** [comment]
先看看显存是不是爆了

**Comment by wildkid1024** [comment]
最好描述一下详细的编译和运行过程信息。
