### ISSUE TITLE
麻烦问下，移动端最小需要多少内存

### ISSUE THREAD

**Issue by StevensPrime** [ztxz16/fastllm#7]

**Comment by ztxz16** [comment]
目前支持最小的是chatglm-6b-int4，移动端5G应该可以跑(我个人在小米mix2, 6G版本上测试过可以跑)

**Comment by StevensPrime** [comment]
用iPhone14promax（6g），如果输出内容很长的话会被系统kill

**Comment by ztxz16** [comment]
> 用iPhone14promax（6g），如果输出内容很长的话会被系统kill
输出长了占用内存确实也会变多.. 估计要8G左右才能比较稳 （好奇问一下，ip14promax上大概什么速度呀）

**Comment by ztxz16** [comment]
> > 目前支持最小的是chatglm-6b-int4，移动端5G应该可以跑(我个人在小米mix2, 6G版本上测试过可以跑)
> 
> 请问速度如何？我再小米12上跑了下，termux的swp最大是6G，速度估计在1token/s，速度很慢，时间久了手机发热严重

跑的是哪个精度？我这边在mix2上大概1token/s，在米10pro上可以跑到3.3 token/s，我没有小米12，但感觉应该不止这个速度呀

**Comment by StevensPrime** [comment]
> > 用iPhone14promax（6g），如果输出内容很长的话会被系统kill
> > 输出长了占用内存确实也会变多.. 估计要8G左右才能比较稳 （好奇问一下，ip14promax上大概什么速度呀）

很慢的，差不多5-8秒输出一个字，😁

**Comment by RamSong** [comment]
我在很老的一台机子上运行，4G运存
chroot 的 Ubuntu22
虚拟了 8G swap
没想到跑起来了，不过很慢，发热严重
