### ISSUE TITLE
make -j 出现报错 _mm256_setm128i was not declared in this scope

### ISSUE THREAD

**Issue by Joris-Fu** [ztxz16/fastllm#71]
cmake 3.24.3
gcc 9.5.0
cuda 10.2

cmake .. -DUSE_CUDA=ON ok，有warning： CUDA_ARCHITECTURE  is empty for target benchmark/fastllm-tool/...

make -j出现报错：

fastllm-master/src/fastllm.cpp: In member function ‘void fastllm::Data::CalcWeightSum()’:
fastllm-master/src/fastllm.cpp:495:31: error: ‘_mm256_set_m128i’ was not declared in this scope
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
fastllm-master/src/fastllm.cpp: In member function ‘void fastllm::Data::CalcWeightSum()’:
fastllm-master/src/fastllm.cpp:495:31: error: ‘_mm256_set_m128i’ was not declared in this scope
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
fastllm-master/src/fastllm.cpp:495:31: note: suggested alternative: ‘_mm256_set_epi8’
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
                               _mm256_set_epi8
fastllm-master/src/fastllm.cpp:495:31: note: suggested alternative: ‘_mm256_set_epi8’
               __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                               ^~~~~~~~~~~~~~~~
                               _mm256_set_epi8
fastllm-master/src/devices/cpu/cpudevice.cpp: In function ‘int fastllm::DotU4U8(uint8_t*, uint8_t*, int)’:
fastllm-master/src/devices/cpu/cpudevice.cpp:108:29: error: ‘_mm256_set_m128i’ was not declared in this scope
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
fastllm-master/src/devices/cpu/cpudevice.cpp:108:29: note: suggested alternative: ‘_mm256_set_epi8’
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
                             _mm256_set_epi8
fastllm-master/src/devices/cpu/cpudevice.cpp: In function ‘int fastllm::DotU4U8(uint8_t*, uint8_t*, int)’:
fastllm-master/src/devices/cpu/cpudevice.cpp:108:29: error: ‘_mm256_set_m128i’ was not declared in this scope
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
fastllm-master/src/devices/cpu/cpudevice.cpp:108:29: note: suggested alternative: ‘_mm256_set_epi8’
             __m256i bytex = _mm256_set_m128i(_mm_srli_epi16(orix, 4), orix);
                             ^~~~~~~~~~~~~~~~
                             _mm256_set_epi8

这个是什么原因，怎么处理呢？

**Comment by wqh17101** [comment]
参考 https://github.com/ztxz16/fastllm/issues/64
