### ISSUE TITLE
如何设置参数，比如top_p, temperature,每次回答的结果都是一样的

### ISSUE THREAD

**Issue by White-Friday** [ztxz16/fastllm#76]

**Comment by ztxz16** [comment]
现在已经支持了

**Comment by louiss007** [comment]
> 现在已经支持了

支持吗，我看python调用接口的源码中这几个参数，都没用吧，大佬帮忙看下，是这块吗？

**Comment by louiss007** [comment]
> 现在已经支持了
支持吗，我看python调用接口的源码中这几个参数，都没用吧，大佬帮忙看下，是这块吗？
![image](https://github.com/ztxz16/fastllm/assets/3722771/abc9fc11-1035-4d57-9540-e6c46eb5cfe8)
