### ISSUE TITLE
使用GLM int4 按照教程添加两行代码后，报错Linear's weight's shape error

### ISSUE THREAD

**Issue by xu-mengnan** [ztxz16/fastllm#79]
<img width="981" alt="图片" src="https://github.com/ztxz16/fastllm/assets/36294047/d9ee5a09-ae53-4a41-8568-3a5cb647ff8a">
机器配置：内存40G，显存11G，可以跑正常GLM int4 模型

**Comment by ztxz16** [comment]
readme里没有讲清楚，from_hf目前不能直接转int4模型，需要先load fp模型，然后from_hf的时候指定dtype为int4
