### ISSUE TITLE
在非移动端设备上推理速度相比原版有提高吗？

### ISSUE THREAD

**Issue by geolvr** [ztxz16/fastllm#9]
非移动端设备+GPU环境

**Comment by ztxz16** [comment]
> 非移动端设备+GPU环境

目前GPU代码实现，预计这周实现
CPU速度有提高的

**Comment by geolvr** [comment]
> > 非移动端设备+GPU环境
> 
> 目前GPU代码实现，预计这周实现 CPU速度有提高的

请问当前的GPU实现，在非移动端上推理速度相比原版有多大提升呢？

**Comment by ztxz16** [comment]
> > > 非移动端设备+GPU环境
> > 
> > 
> > 目前GPU代码实现，预计这周实现 CPU速度有提高的
> 
> 请问当前的GPU实现，在非移动端上推理速度相比原版有多大提升呢？

要看具体的设备，等之后优化好了我准备做一个页面贴benchmark数据
目前在我的4090上，原版大概20 token/s 左右，fastllm 50 token / s左右

**Comment by ztxz16** [comment]
> > > 非移动端设备+GPU环境
> > 
> > 
> > 目前GPU代码实现，预计这周实现 CPU速度有提高的
> 
> 请问当前的GPU实现，在非移动端上推理速度相比原版有多大提升呢？

目前有了不少优化，4090上速度可以达到95 token / s左右了
