### ISSUE TITLE
请问对比过原模型和现在模型的输出效果吗？谢谢。

### ISSUE THREAD

**Issue by neverstoplearn** [ztxz16/fastllm#92]

**Comment by ztxz16** [comment]
对比过fp模型在tokenizer一致的情况下，到logits层的误差在1e-5级别，基本是一致的
不过c++的tokenizer和python没有对齐，现在可以直接用py的tokenizer

**Comment by neverstoplearn** [comment]
> 对比过fp模型在tokenizer一致的情况下，到logits层的误差在1e-5级别，基本是一致的 不过c++的tokenizer和python没有对齐，现在可以直接用py的tokenizer

好的谢谢

**Comment by micrazy** [comment]
> 对比过fp模型在tokenizer一致的情况下，到logits层的误差在1e-5级别，基本是一致的 不过c++的tokenizer和python没有对齐，现在可以直接用py的tokenizer

请问作者，如何使用flm的chat接口呢？ 有没有相关的接口文档@ztxz16
